# Generated by Django 5.0.2 on 2024-03-13 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrasSizes',
            fields=[
                ('idBraSize', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'BrasSizes',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='EcologicalCategories',
            fields=[
                ('idEcologicalCategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'ecologicalCategories',
            },
        ),
        migrations.CreateModel(
            name='GenderCategories',
            fields=[
                ('idGenderCategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genderCategories',
            },
        ),
        migrations.CreateModel(
            name='GeneralSizes',
            fields=[
                ('idGeneralSize', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'generalSizes',
            },
        ),
        migrations.CreateModel(
            name='PantsSizes',
            fields=[
                ('idPantSize', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pantsSizes',
            },
        ),
        migrations.CreateModel(
            name='ShoesSizesUS',
            fields=[
                ('idShoeSize', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            options={
                'db_table': 'shoesSizes',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=101)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='product_image/')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stores')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductRatings',
            fields=[
                ('idProductRating', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('idRaterUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'productRatings',
            },
        ),
        migrations.CreateModel(
            name='ProductPantsSizes',
            fields=[
                ('idProductPantSize', models.AutoField(primary_key=True, serialize=False)),
                ('quantityAvailable', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idPantSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pantssizes')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': '´productPantsSizes',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('idProductImage', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'productImages',
            },
        ),
        migrations.CreateModel(
            name='ProductGeneralSizes',
            fields=[
                ('idProductGeneralSize', models.AutoField(primary_key=True, serialize=False)),
                ('quantityAvailable', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idGeneralSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.generalsizes')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'productGeneralSizes',
            },
        ),
        migrations.CreateModel(
            name='ProductGenderCategories',
            fields=[
                ('idProductGenderCategory', models.AutoField(primary_key=True, serialize=False)),
                ('idGenderCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gendercategories')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'productGenderCategories',
            },
        ),
        migrations.CreateModel(
            name='ProductEcologicalCategories',
            fields=[
                ('idProductEcologicalCategory', models.AutoField(primary_key=True, serialize=False)),
                ('idEcologicalCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ecologicalcategories')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'productEcologicalCategories',
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('idProductCategory', models.AutoField(primary_key=True, serialize=False)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'productCategories',
            },
        ),
        migrations.CreateModel(
            name='ProductBrasSizes',
            fields=[
                ('idProductBrasSize', models.AutoField(primary_key=True, serialize=False)),
                ('quantityAvailable', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idBraSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brassizes')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'productBrasSizes',
            },
        ),
        migrations.CreateModel(
            name='ProductShoesSizesUS',
            fields=[
                ('idProductShoesSizeUS', models.AutoField(primary_key=True, serialize=False)),
                ('quantityAvailable', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('idShoeSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shoessizesus')),
            ],
            options={
                'db_table': 'productShoesSizesUS',
            },
        ),
    ]
